<?php

/**
 * @file
 * Contains attendance_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function attendance_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the attendance_custom module.
    case 'help.page.attendance_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to handle site functionalities') . '</p>';
      return $output;

    default:
  }
}
